### ISSUE TITLE
Select Feld TYP Styling hinzufügen

### ISSUE THREAD

**Issue by Sulkar** [Sulkar/SQLverine#14]
Select Feld TYP benötigt noch ein Styling. Weitere Select Felder die in SQLverine genutzt werden:
- Select Tabellen (grün)
- Select Spalten (rot)
- Select Operatoren (gelb)

![image](https://user-images.githubusercontent.com/10349796/118234120-3528f180-b493-11eb-940e-5aa38dfc5e28.png)

**Comment by voetzi** [comment]
Button gestyled
