### ISSUE TITLE
CREATE TABLE Statements implementieren

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#3]

**Comment by Sulkar** [comment]
Erste Version eingebaut: f10bf4c2a08936358c3d97187e78eb1578994066

**ToDo**:
- Komma am Ende der Spaltenzeile anfügen, passend der aktuellen Auswahl (letzte Spaltenzeile bekommt kein Komma, was passiert wenn Spaltenzeilen gelöscht, ergänzt werden?)
- FOREIGN KEY muss als eigenständige Zeile ans Create Statement angehängt werden?
- FOREIGN KEY ('spalte') REFERENCES tabelle ('spalte')

![image](https://user-images.githubusercontent.com/10349796/118278374-3d505380-b4ca-11eb-9b9a-2adbd907042b.png)

**Comment by Sulkar** [comment]
Komma wird am Ende einer Spaltenzeile eingefügt, wenn im Anschluss eine weitere Spaltenzeile kommt. Dies wird mit Hilfe der "cleanSQLCode()" Funktion gemacht, die beim Hinzufügen von Spalten und beim Löschen aufgerufen wird. Dort können weitere "Cleans" die benötigt werden eingebaut werden.

Siehe: 0e60f7cd5970751999bad33c8e2b9c630ecaaa5f

**Comment by Sulkar** [comment]
FOREIGN KEY Funktionalität hinzugefügt mit dynamischer Spaltenwahl. Siehe: 89d4d348dfd3bf3f19e455967aeef3fed63b6a28
![image](https://user-images.githubusercontent.com/10349796/118366063-82928500-b59f-11eb-8e1f-22ab94193cfd.png)
