### ISSUE TITLE
Tabellenname in Ergebnisanzeige

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#42]
Bei JOINs sollte der Tabellenname auch im Spaltenkopf stehen, so dass die Spaltennamen den Tabellen zuordenbar sind.

**Comment by Sulkar** [comment]
Das ist nur sauber möglich, wenn wir die AS Syntax einbauen:

```sql
SELECT schueler.*, klasse.name AS klassenname FROM schueler ...
```
Wenn eine Spalte im SELECT Statement ausgewählt ist, kann ein neuer Codeblock: **AS ___** hinzugefügt werden.

**Comment by Sulkar** [comment]
AS ___ wurde hinzugefügt. Hier ein Beispiel einer Bundesliga Datenbank:
![image](https://user-images.githubusercontent.com/10349796/144062178-7f2b3500-8ca7-4ebb-8d06-022391a22bdd.png)

siehe: bba1d6e8f899ab095fe9eae84180538483d61ce1
