### ISSUE TITLE
Fehler in CREATE Statement

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#47]
Definiert man mehrere FKs wird wenn eine Spalte gewählt wird immer der Tabellenname samt Punkt vor die Spalte gehängt. Dies darf bei CREATE Statements nicht passieren. (Bei JOINS allerdings schon)

**Comment by Sulkar** [comment]
Tabellennamen werden beim CREATE_FOREIGN_KEY Element nicht mehr mit angehängt. Siehe: 16d160751a92d0c45fb178141a770eee612bf1fa
