### ISSUE TITLE
Dialog beim Verlassen der Seite

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#49]
Es soll verhindert werden, dass ein versehentliche(r) Reload/Browser zurück etc. alle Eingaben zurücksetzt.

**Comment by voetzi** [comment]
Stichwort: WindowEventHandlers.onbeforeunload

**Comment by Sulkar** [comment]
Ich würde den Dialog nur anzeigen, wenn etwas verändert wurde. Also wenn
- eine Aufgabe gelöst wurde.
- wenn Daten in der Datenbank verändert wurden (UPDATE, INSERT, DELETE, ALTER, CREATE)
- ...

Wir könnten in der **VerineDatabase** Klasse so eine Methode erstellen, die ein Attribut auf True/False setzt und welches beim Verlassen der Seite abgefragt wird.

**Comment by voetzi** [comment]
Gute Idee!

**Comment by Sulkar** [comment]
Dialog wird nun nur angezeigt, wenn Daten in der aktuellen DB geändert wurden. Siehe: 1146f1adf79b8a73165713cc2f492754b8f41870
