### ISSUE TITLE
Aufgabenprüfung bei Gleitkommazahlen

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#51]
Die Aufgabenprüfung bei Gleitkommazahlen funktioniert nicht.
![image](https://user-images.githubusercontent.com/10349796/145559106-b0fd2b3d-df13-4663-955c-c43c29978340.png)

**Comment by Sulkar** [comment]
Was funktioniert da nicht? Oder war das die Sache mit dem Import von Daten im Autorentool, dass das Komma beim Import in einen Punkt umgewandelt werden?

**Comment by Sulkar** [comment]
Hier tritt das Problem auch auf, wenn URLs abgefragt werden sollen:
![image](https://user-images.githubusercontent.com/10349796/145559331-c890074c-fd42-4673-8ec0-2f8ef2521f5b.png)

**Comment by Sulkar** [comment]
Die Antworteneingabe wird in VerineDatabase.js geparst:
![image](https://user-images.githubusercontent.com/10349796/145560365-ea990809-cc3d-403e-bf94-a24c9894d5c5.png)

**Comment by Sulkar** [comment]
Funktioniert nun. Siehe: b789d260b8b9e454563b100c61e0a5605ba82e54

Test:
![image](https://user-images.githubusercontent.com/10349796/145563554-4c0b7a4d-3c3c-42e9-b9ca-70f76695ab55.png)
