### ISSUE TITLE
Befehlt führt zu Fehler

### ISSUE THREAD

**Issue by voetzi** [Sulkar/SQLverine#72]
Das aus der Parser Testsuite nachgebaute Query führt zum Fehler. Erlauben wir evtl. zuviel?

![Bildschirmfoto 2022-04-16 um 23 30 38](https://user-images.githubusercontent.com/17147929/163691994-927eae2d-eec0-42b9-a03e-ff1bce7d08f4.png)

**Comment by Sulkar** [comment]
Für order by MAX benötigt man immer? eine Gruppierung: 

SELECT * FROM schueler GROUP BY klasse_id ORDER BY MAX(geburtsdatum)

**Comment by voetzi** [comment]
Dann liegts nur am Parser Test ;-)
